# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0004_auto_20170418_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
