# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0005_auto_20170424_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagged',
            name='article',
        ),
        migrations.RemoveField(
            model_name='tagged',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='minitwitter.Hashtag'),
        ),
        migrations.DeleteModel(
            name='Tagged',
        ),
    ]
