# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0006_auto_20170426_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minitwitter.Member')),
            ],
        ),
    ]
