# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0007_commnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commnet',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minitwitter.Article'),
        ),
    ]
