# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwitter', '0008_commnet_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
